name: HelloWorld
author: SalmonDE
main: SalmonDE\HelloWorld\Main
api: [3.0.0-ALPHA5, 3.0.0-ALPHA6]
version: 1.1.0
commands:
    helloworld:
        usage: "/helloworld <player>"
        description: "Introduce someone into the beautiful world of HelloWorld"
        permission: helloworld
permissions:
    helloworld:
